audit_checklist_dict = {'questions': [{'question': 'Czy umowa najmu została zawarta na piśmie, jeśli dotyczy nieruchomości lub pomieszczenia na czas dłuższy niż rok?',
   'legal_basis': [{'article': 'Art. 660',
     'paragraph': None,
     'description': 'Umowa najmu nieruchomości lub pomieszczenia na czas dłuższy niż rok powinna być zawarta na piśmie.'}],
   'possible_issues': ['Umowa może być uznana za zawartą na czas nieoznaczony.'],
   'priority': 1,
   'category': 'Forma umowy',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa jest w formie pisemnej.'},
  {'question': 'Czy czynsz został określony w umowie?',
   'legal_basis': [{'article': 'Art. 659',
     'paragraph': None,
     'description': 'Najemca zobowiązuje się płacić wynajmującemu umówiony czynsz.'}],
   'possible_issues': ['Brak określenia czynszu może prowadzić do sporów dotyczących płatności.'],
   'priority': 1,
   'category': 'Elementy konieczne umowy',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzulę dotyczącą czynszu.'},
  {'question': 'Czy umowa określa czas trwania najmu?',
   'legal_basis': [{'article': 'Art. 659',
     'paragraph': None,
     'description': 'Umowa najmu może być zawarta na czas oznaczony lub nieoznaczony.'}],
   'possible_issues': ['Brak określenia czasu trwania może prowadzić do niejasności co do zakończenia umowy.'],
   'priority': 2,
   'category': 'Czas trwania',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzulę dotyczącą czasu trwania.'},
  {'question': 'Czy wynajmujący wydał rzecz w stanie przydatnym do umówionego użytku?',
   'legal_basis': [{'article': 'Art. 662',
     'paragraph': None,
     'description': 'Wynajmujący powinien wydać najemcy rzecz w stanie przydatnym do umówionego użytku.'}],
   'possible_issues': ['Najemca może żądać obniżenia czynszu lub wypowiedzieć umowę.'],
   'priority': 1,
   'category': 'Obowiązki stron',
   'note': None,
   'validation_hint': 'Sprawdź stan rzeczy w momencie wydania.'},
  {'question': 'Czy umowa zawiera postanowienia dotyczące napraw i utrzymania rzeczy?',
   'legal_basis': [{'article': 'Art. 662',
     'paragraph': None,
     'description': 'Wynajmujący powinien utrzymywać rzecz w stanie przydatnym do użytku.'},
    {'article': 'Art. 663',
     'paragraph': None,
     'description': 'Najemca może wyznaczyć wynajmującemu termin na wykonanie koniecznych napraw.'}],
   'possible_issues': ['Brak postanowień może prowadzić do sporów dotyczących odpowiedzialności za naprawy.'],
   'priority': 2,
   'category': 'Utrzymanie i naprawy',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące napraw i utrzymania.'},
  {'question': 'Czy umowa określa terminy płatności czynszu?',
   'legal_basis': [{'article': 'Art. 669',
     'paragraph': None,
     'description': 'Najemca obowiązany jest uiszczać czynsz w terminie umówionym.'}],
   'possible_issues': ['Brak określenia terminów może prowadzić do opóźnień w płatnościach.'],
   'priority': 1,
   'category': 'Płatności',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzulę dotyczącą terminów płatności.'},
  {'question': 'Czy umowa zawiera postanowienia dotyczące możliwości wypowiedzenia najmu?',
   'legal_basis': [{'article': 'Art. 673',
     'paragraph': None,
     'description': 'Określenie terminów i sposobu wypowiedzenia najmu.'}],
   'possible_issues': ['Brak postanowień może prowadzić do niejasności co do możliwości zakończenia umowy.'],
   'priority': 1,
   'category': 'Wypowiedzenie i zakończenie',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące wypowiedzenia.'},
  {'question': 'Czy najemca ma prawo do podnajmu lub oddania rzeczy do bezpłatnego używania?',
   'legal_basis': [{'article': 'Art. 668',
     'paragraph': None,
     'description': 'Najemca może oddać rzecz osobie trzeciej, jeżeli umowa mu tego nie zabrania.'}],
   'possible_issues': ['Brak zgody wynajmującego może prowadzić do naruszenia umowy.'],
   'priority': 3,
   'category': 'Prawa stron',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące podnajmu.'},
  {'question': 'Czy umowa zawiera postanowienia dotyczące rękojmi za wady rzeczy?',
   'legal_basis': [{'article': 'Art. 664',
     'paragraph': None,
     'description': 'Najemca może żądać obniżenia czynszu lub wypowiedzieć umowę z powodu wad rzeczy.'}],
   'possible_issues': ['Brak postanowień może prowadzić do sporów dotyczących odpowiedzialności za wady.'],
   'priority': 2,
   'category': 'Obowiązki stron',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące rękojmi.'},
  {'question': 'Czy umowa określa sposób używania rzeczy najętej?',
   'legal_basis': [{'article': 'Art. 666',
     'paragraph': None,
     'description': 'Najemca powinien używać rzeczy w sposób określony w umowie.'}],
   'possible_issues': ['Brak określenia sposobu używania może prowadzić do nieporozumień.'],
   'priority': 3,
   'category': 'Obowiązki stron',
   'note': None,
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące sposobu używania rzeczy.'},
  {'question': 'Czy umowa najmu została zawarta w formie pisemnej?',
   'legal_basis': [{'article': 'Art. 660',
     'paragraph': None,
     'description': 'Umowa najmu powinna być zawarta w formie pisemnej, jeżeli dotyczy lokalu mieszkalnego.'}],
   'possible_issues': ['Brak dowodu na zawarcie umowy',
    'Trudności w egzekwowaniu praw z umowy'],
   'priority': 1,
   'category': 'Forma umowy',
   'note': 'Zaleca się zawsze spisywać umowę najmu.',
   'validation_hint': 'Sprawdź, czy umowa jest podpisana przez obie strony.'},
  {'question': 'Czy określono czas trwania najmu?',
   'legal_basis': [{'article': 'Art. 688',
     'paragraph': None,
     'description': 'Czas trwania najmu powinien być określony, w przeciwnym razie stosuje się przepisy o wypowiedzeniu.'}],
   'possible_issues': ['Niepewność co do długości najmu',
    'Problemy z wypowiedzeniem umowy'],
   'priority': 1,
   'category': 'Czas trwania',
   'note': 'Zaleca się określenie czasu trwania umowy.',
   'validation_hint': 'Sprawdź, czy w umowie jest zapis o czasie trwania najmu.'},
  {'question': 'Czy strony umowy określiły obowiązki wynajmującego i najemcy?',
   'legal_basis': [{'article': 'Art. 681',
     'paragraph': None,
     'description': 'Najemca ma obowiązek dokonywania drobnych napraw.'},
    {'article': 'Art. 683',
     'paragraph': None,
     'description': 'Najemca powinien stosować się do porządku domowego.'}],
   'possible_issues': ['Niejasności w zakresie odpowiedzialności za naprawy',
    'Problemy z egzekwowaniem porządku domowego'],
   'priority': 1,
   'category': 'Obowiązki stron',
   'note': 'Obowiązki powinny być jasno określone w umowie.',
   'validation_hint': 'Sprawdź, czy umowa zawiera szczegółowy opis obowiązków.'},
  {'question': 'Czy umowa zawiera zapisy dotyczące terminów płatności czynszu?',
   'legal_basis': [{'article': 'Art. 685.1',
     'paragraph': None,
     'description': 'Wynajmujący może podwyższyć czynsz, wypowiadając dotychczasową wysokość czynszu.'}],
   'possible_issues': ['Niejasności co do wysokości czynszu',
    'Problemy z terminowością płatności'],
   'priority': 1,
   'category': 'Płatności',
   'note': 'Zaleca się określenie terminów płatności w umowie.',
   'validation_hint': 'Sprawdź, czy umowa zawiera szczegóły dotyczące płatności.'},
  {'question': 'Czy umowa przewiduje możliwość odstąpienia od umowy?',
   'legal_basis': [{'article': 'Art. 682',
     'paragraph': None,
     'description': 'Najemca może wypowiedzieć najem bez zachowania terminów wypowiedzenia w przypadku wad lokalu.'}],
   'possible_issues': ['Brak możliwości rozwiązania umowy w przypadku problemów z lokalem',
    'Trudności w egzekwowaniu praw najemcy'],
   'priority': 1,
   'category': 'Wypowiedzenie i zakończenie',
   'note': 'Zaleca się określenie warunków odstąpienia w umowie.',
   'validation_hint': 'Sprawdź, czy umowa zawiera klauzule dotyczące wypowiedzenia.'}],
 'checklist_name': 'Audyt umowy najmu',
 'version': '1.0',
 'applicable_law_version': 'Dz.U.2024.0.1061'}
